spring:
  profiles:
    active:
      - dev
---
server:
 port: 7001
eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false    #是否在eureka中注册自已
    service-url:
        defaultZone: http://admin:a@localhost:7001/eureka
  instance:             # eureak实例定义
    hostname: eureka # 定义 Eureka 实例所在的主机名称
spring:
  profiles: dev
  security:
    user:
      name: admin
      password: a
  application:
    name: microservice-config-eureka
---
server:
 port: 7002
eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
        defaultZone: http://admin:a@localhost:7002/eureka
  instance:             # eureak实例定义
    hostname: eureka # 定义 Eureka 实例所在的主机名称
spring:
  profiles: beta
  security:
    user:
      name: admin
      password: a
  application:
    name: microcloud-config-eureka
